name: tsseg-env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - cython
  - pip
  - numpy
  - scikit-learn
  - numba
  - pytest
  - pandas
  - scipy
  - statsmodels
  - pooch
  - future
  - pytorch
  # - pytorch-cuda=11.8
  - pip:
    - .[torch,prophet,patss,accelerators,docs,aeon,tglad]
    - tensorflow==2.17.0
    - keras-tcn==3.5.0